server:
  port: 8081

spring:
  application:
    name: sts-stock
  cloud:
    config:
#      discovery:
#        enabled: true # 开启通过服务来访问配置中心服务
#        service-id: sts-config # 配置中心注册的服务名
      profile: dev #配置在本机环境变量中，dev-in表示内网开发环境，dev-out表示外网开发环境
      label: master #最好要指定label，否则在cloud bus refresh的时候，有一定的概率找不到配置文件，进而无法更新配置信息
      uri: http://localhost:8030/
#      name: ${spring.application.name}
  data:
    mongodb:
      database: stock_a
      host: 127.0.0.1 #39.108.217.50
      port: 27017
      username: collect
      password: collect
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    prefer-same-zone-eureka: true
    registry-fetch-interval-seconds: 5 # 向注册服务获取当前服务列表（缺省为30s）

feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000 #feign 超时默认为1000毫秒
logging:
  file: logs/${spring.application.name}.log