server:
  port: 8888
spring:
  application:
    name: sts-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
#      routes:
#      - id: sts-stock
#        url: http://localhost:8081
#        predicates:
#        - Method=GET

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
